---
title: "MSC All Subjects RSFC Matrices"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressMessages(library(pander))
suppressMessages(library(magrittr))
suppressMessages(library(superheat))
suppressMessages(library(ExPosition))
suppressMessages(library(gridExtra))
suppressMessages(library(ggplotify))
suppressMessages(library(grid))
suppressMessages(library(pals))
# Read functions -----------------------------------
tool.path <- "../tools/"
source(paste0(tool.path,"SScomm.R")) # SScomm.R: computes sums of squares of a square matrix according to a design matrix
source(paste0(tool.path,"vec2sqmat.R"))
source(paste0(tool.path,"getVoxDes.R"))

#### == DEFINE Parameters (e.g., subj name, paths) == ####
# This section will hopefully become parameterized for RMD in the future 

parcelfile2read <- c("/sub-MSC01_node_parcel_comm.txt",
                     "/sub-MSC02_node_parcel_comm.txt",
                     "/sub-MSC03_node_parcel_comm.txt",
                     "/sub-MSC04_node_parcel_comm.txt",
                     "/sub-MSC05_node_parcel_comm.txt",
                     "/sub-MSC06_node_parcel_comm.txt",
                     "/sub-MSC07_node_parcel_comm.txt",
                     "/sub-MSC08_node_parcel_comm.txt",
                     "/sub-MSC09_node_parcel_comm.txt",
                     "/sub-MSC10_node_parcel_comm.txt"
                     )
subj.name <- c("sub01","sub02", "sub03",
               "sub04","sub05", "sub06",
               "sub07","sub08", "sub09","sub010")

```

```{r community_list, echo = FALSE, fig.height= 10, fig.width = 2}
# rename communities
#--- read the file with community information: label number & community name & color & abbreviation for community name
parcel.comm.path <- "../data/parcel_community"
CommName <- read.csv("../data/parcel_community/systemlabel.txt",header = FALSE)
colnames(CommName) <- c("Comm", "CommLabel","CommColor","CommLabel.short")
CommName[,'Community'] <- c("UnAssign", "Default","lateral Visual","Frontoparietal",
                            "medial Visual","dorsal Attention","Premotor",
                            "ventral Attention","Salience","Cingular opercular",
                            "Sensorimotor - hand","Sensorimotor - face","Auditory",
                            "anterior Medial temporal","posterior Medial temporal",
                            "Parietal memory","Context","Sensorimotor - foot", 
                            "Unknown","Unknown","Unknown","UnKnown","UnKnown")
pander::pander(CommName[,c("Comm", "Community","CommLabel.short")])

```

```{r data_info}
# read parcel labels for each subject
parcel.comm.path <- "../data/parcel_community"
parcel.list <- lapply(1:length(parcelfile2read), function(x){
                      parcel <- read.table(paste0(parcel.comm.path, parcelfile2read[x]),sep = ",")
                      getVoxDes(parcel,CommName)
                      })
names(parcel.list) <- subj.name

#-- Create colors for heatmap 
labelcol <- list()
textcol <- list()
for(i in 1:length(subj.name)){
  labelcol[[i]] <- parcel.list[[i]]$Comm.col$gc[order(rownames(parcel.list[[i]]$Comm.col$gc))]
  names(labelcol)[i] <- subj.name[i]
  
  textcol[[i]] <- rep("black", length(labelcol[[i]]))
  textcol[[i]][as(colorspace::hex2RGB(labelcol[[i]]), "polarLUV")@coords[,1] < 35] <- "white"  # Convert hex2RGB to lum
}

```

## Here are the heatmaps of all 10 sessions arranged by each subject 

```{r setup_matrix, echo = FALSE, include = FALSE, fig.show='hide'}
### Make these not objects, but part of a list? ### MYC NEED TO CHANGE 20190404
# read examplar data
zmat.path <- "../data/zmat"
#--- plot heatmap
hmaplist <- list()
hmaplist_i <- 1
for(subj.count in 1:length(parcel.list)){
  load(sprintf("%s/sub-MSC%02d_zcube_rcube.RData",zmat.path,subj.count))
  hmaplist[[subj.count]] <- list()
  for(session.count in 1:dim(cubes$rcube)[3]){
    # heat map of correlation matrices
    hmap.name <- sprintf("sub%02d_hmap%s", subj.count, session.count)
    hmaplist[[subj.count]][[session.count]] <- superheat(cubes$rcube[,,session.count],
                                membership.cols = parcel.list[[subj.count]]$vox.des$Comm.rcd,
                                membership.rows = parcel.list[[subj.count]]$vox.des$Comm.rcd,
                                clustering.method = NULL,
                                heat.col.scheme = "viridis",
                                left.label.size = 0.08,
                                bottom.label.size = 0.05,
                                y.axis.reverse = TRUE,
                                left.label.col = labelcol[[subj.count]], # order by community name
                                bottom.label.col = labelcol[[subj.count]],
                                left.label.text.size = 3,
                                bottom.label.text.size = 2,
                                left.label.text.col = textcol[[subj.count]],
                                bottom.label.text.col = textcol[[subj.count]],
                                left.label.text.alignment = "left",
                                title = sprintf("Correlation matrix of #%s session",session.count)
                                )$plot
  }
}

```

```{r plot_all_sub_session_hmap, echo=F, fig.height=20, fig.width= 40}
for(i in 1:length(hmaplist)){
  print(sprintf("%s", subj.name[i]))
  do.call(grid.arrange, c(hmaplist[[i]], ncol=5))
}
```

## Here are the double-centered heamaps of all subjects

```{r setup_matrix_dc, echo = FALSE, include = FALSE, fig.show='hide'}
### Make these not objects, but part of a list? ### MYC NEED TO CHANGE 20190404
# read examplar data
zmat.path <- "../data/zmat"

#--- plot heatmap
hmaplist_DC <- list()
hmaplist_DC_i <- 1
for(subj.count in 1:length(parcel.list)){
  load(sprintf("%s/sub-MSC%02d_zcube_rcube_DC.RData",zmat.path,subj.count))
  hmaplist_DC[[subj.count]] <- list()
  for(session.count in 1:dim(s)[3]){
    # heat map of correlation matrices
    hmap.name <- sprintf("sub%02d_hmap%s", subj.count, session.count)
    hmaplist_DC[[subj.count]][[session.count]] <- superheat(s[,,session.count],
                                membership.cols = parcel.list[[subj.count]]$vox.des$Comm.rcd,
                                membership.rows = parcel.list[[subj.count]]$vox.des$Comm.rcd,
                                clustering.method = NULL,
                                heat.col.scheme = "viridis",
                                left.label.size = 0.08,
                                bottom.label.size = 0.05,
                                y.axis.reverse = TRUE,
                                left.label.col = labelcol[[subj.count]], # order by community name
                                bottom.label.col = labelcol[[subj.count]],
                                left.label.text.size = 3,
                                bottom.label.text.size = 2,
                                left.label.text.col = textcol[[subj.count]],
                                bottom.label.text.col = textcol[[subj.count]],
                                left.label.text.alignment = "left",
                                title = sprintf("Double-centered correlation matrix of #%s session",session.count)
                                )$plot
  }
}

```

```{r plot_all_sub_session_hmap_dc, echo=F, fig.height=20, fig.width= 40}
for(i in 1:length(hmaplist_DC)){
  print(sprintf("%s", subj.name[i]))
  do.call(grid.arrange, c(hmaplist_DC[[i]], ncol=5))
}
```

## Here are the smoothed heatmaps of all 10 sessions arranged by each subject 

```{r setup_matrix_smoothed, echo = FALSE, include = FALSE, fig.show='hide'}
### Make these not objects, but part of a list? ### MYC NEED TO CHANGE 20190404
# read examplar data
zmat.path <- "../data/zmat"
#--- plot heatmap
hmaplist.mean <- list()
hmaplist.mean_i <- 1
for(subj.count in 1:length(parcel.list)){
  load(sprintf("%s/sub-MSC%02d_zcube_rcube.RData",zmat.path,subj.count))
  hmaplist.mean[[subj.count]] <- list()
  for(session.count in 1:dim(cubes$rcube)[3]){
    # heat map of correlation matrices
    hmap.name <- sprintf("sub%02d_hmap%s", subj.count, session.count)
    hmaplist.mean[[subj.count]][[session.count]] <- superheat(cubes$rcube[,,session.count],
                                membership.cols = parcel.list[[subj.count]]$vox.des$Comm.rcd,
                                membership.rows = parcel.list[[subj.count]]$vox.des$Comm.rcd,
                                clustering.method = NULL,
                                heat.col.scheme = "viridis",
                                left.label.size = 0.08,
                                bottom.label.size = 0.05,
                                y.axis.reverse = TRUE,
                                left.label.col = labelcol[[subj.count]], # order by community name
                                bottom.label.col = labelcol[[subj.count]],
                                left.label.text.size = 3,
                                bottom.label.text.size = 2,
                                left.label.text.col = textcol[[subj.count]],
                                bottom.label.text.col = textcol[[subj.count]],
                                left.label.text.alignment = "left",
                                smooth.heat = TRUE,
                                smooth.heat.type = "mean",
                                title = sprintf("Correlation matrix of #%s session",session.count)
                                )$plot
  }
}

```


```{r plot_all_session_hmap, echo=F, fig.height=20, fig.width= 40}
for(i in 1:length(hmaplist.mean)){
  print(sprintf("%s", subj.name[i]))
  do.call(grid.arrange, c(hmaplist.mean[[i]], ncol=5))
}
```

## Here are the smoothed heatmaps of all subjects arranged by sessions


```{r plot_all_sub__hmap, echo=F, fig.height=20, fig.width= 40}
n.session <- dim(cubes$rcube)[3]
n.subject <- 1:length(parcel.list)
for(i in 1:n.session){
  print(sprintf("session#%d", i))
  do.call(grid.arrange, c(lapply(hmaplist.mean, `[[`, i), ncol=5))
}
```

