


We can also show the factor scores for network edges as square matrix of sub01 (MSC 01) and sub02 (MSC 08)

```{r squaremat_fi, echo=F, fig.show = 'hide'}
fj1_s1_sqmat <- vec2sqmat(svd.res$ExPosition.Data$fj[gtlabel$subjects_label=="sub01",1])
fj1_s2_sqmat <- vec2sqmat(svd.res$ExPosition.Data$fj[gtlabel$subjects_label=="sub02",1])

fj2_s1_sqmat <- vec2sqmat(svd.res$ExPosition.Data$fj[gtlabel$subjects_label=="sub01",2])
fj2_s2_sqmat <- vec2sqmat(svd.res$ExPosition.Data$fj[gtlabel$subjects_label=="sub02",2])

heat_fj1_s1 <- superheat(fj1_s1_sqmat, y.axis.reverse = T,
                    membership.rows =parcel.list$sub01$vox.des$Comm.rcd,
                    membership.cols =parcel.list$sub01$vox.des$Comm.rcd,                    
                    left.label.col = labelcol$sub01,
                    bottom.label.col = labelcol$sub01,
                    left.label.size = 0.08,
                    bottom.label.size = 0.05,
                    extreme.values.na = FALSE,
                    heat.lim = c(-.005, .005),
                    heat.pal = kovesi.diverging_bwr_40_95_c42(200),
                    heat.pal.values = c(0,0.35,0.5,0.65,1),
                    left.label.text.size = 3,
                    bottom.label.text.size = 2,
                    left.label.text.col = textcol$sub01, 
                    bottom.label.text.col = textcol$sub01, 
                    title="sub01, dim1")

heat_fj1_s2 <- superheat(fj1_s2_sqmat, y.axis.reverse = T,
                    membership.rows =parcel.list$sub02$vox.des$Comm.rcd,
                    membership.cols =parcel.list$sub02$vox.des$Comm.rcd,
                    left.label.col = labelcol$sub02,
                    bottom.label.col = labelcol$sub02,
                    left.label.size = 0.08,
                    bottom.label.size = 0.05,
                    extreme.values.na = FALSE,
                    heat.lim = c(-.005, .005),
                    heat.pal = kovesi.diverging_bwr_40_95_c42(200),
                    heat.pal.values = c(0,0.35,0.5,0.65,1),
                    left.label.text.size = 3,
                    bottom.label.text.size = 2,
                    left.label.text.col = textcol$sub02,
                    bottom.label.text.col = textcol$sub02,
                    title="sub02, dim1")

heat_fj2_s1 <- superheat(fj2_s1_sqmat, y.axis.reverse = T,
                    membership.rows =parcel.list$sub01$vox.des$Comm.rcd,
                    membership.cols =parcel.list$sub01$vox.des$Comm.rcd,                    
                    left.label.col = labelcol$sub01,
                    bottom.label.col = labelcol$sub01,
                    left.label.size = 0.08,
                    bottom.label.size = 0.05,
                    extreme.values.na = FALSE,
                    heat.lim = c(-.005, .005),
                    heat.pal = kovesi.diverging_bwr_40_95_c42(200),
                    heat.pal.values = c(0,0.35,0.5,0.65,1),
                    left.label.text.size = 3,
                    bottom.label.text.size = 2,
                    left.label.text.col = textcol$sub01, 
                    bottom.label.text.col = textcol$sub01, 
                    title="sub01, dim2")

heat_fj2_s2 <- superheat(fj2_s2_sqmat, y.axis.reverse = T,
                    membership.rows =parcel.list$sub02$vox.des$Comm.rcd,
                    membership.cols =parcel.list$sub02$vox.des$Comm.rcd,                    
                    left.label.col = labelcol$sub02,
                    bottom.label.col = labelcol$sub02,
                    left.label.size = 0.08,
                    bottom.label.size = 0.05,
                    extreme.values.na = FALSE,
                   #  heat.lim = c(-.6, .6),
                    heat.pal = kovesi.diverging_bwr_40_95_c42(200),
                    heat.pal.values = c(0,0.35,0.5,0.65,1),
                    left.label.text.size = 3,
                    bottom.label.text.size = 2,
                    left.label.text.col = textcol$sub02, 
                    bottom.label.text.col = textcol$sub02, 
                    title="sub02, dim2")
```

```{r grid_heat_fi, echo=F, fig.height=15, fig.width=14}
gridExtra::grid.arrange(as.grob(heat_fj1_s1$plot), as.grob(heat_fj1_s2$plot), 
                        as.grob(heat_fj2_s1$plot), as.grob(heat_fj2_s2$plot), 
                        ncol=2,
                        top = textGrob("Node x Node Matrix of Factor Score: Dim 1 & Dim 2",gp=gpar(fontsize=18,font=3)))
```

Factor score (Dim 1) in square matrix that have significant contribution only
```{r, squaremat_sigfj1, echo=F, fig.show = 'hide'}
fj_sig <- svd.res$ExPosition.Data$fj
fj_sig[!importantEdg1] <- 0
fj1_sub1_sig_sqmat <- vec2sqmat(fj_sig[gtlabel$subjects_label=="sub01",1])
fj1_sub2_sig_sqmat <- vec2sqmat(fj_sig[gtlabel$subjects_label=="sub02",1])

heat_sigfj1_sub1 <- superheat(fj1_sub1_sig_sqmat, y.axis.reverse = T,
                             membership.rows =parcel.list$sub01$vox.des$Comm.rcd,
                             membership.cols =parcel.list$sub01$vox.des$Comm.rcd,                    
                             left.label.col = labelcol$sub01,
                             bottom.label.col = labelcol$sub01,
                             left.label.size = 0.08,
                             bottom.label.size = 0.05,
                             extreme.values.na = FALSE,
                             heat.lim = c(-.005, .005),
                             heat.pal = kovesi.diverging_bwr_40_95_c42(200),
                             heat.pal.values = c(0,0.35,0.5,0.65,1),
                             left.label.text.size = 3,
                             bottom.label.text.size = 2,
                             left.label.text.col = textcol$sub01, 
                             bottom.label.text.col = textcol$sub01, 
                             title="sub1: significant contribution")

heat_sigfj1_sub2 <- superheat(fj1_sub2_sig_sqmat, y.axis.reverse = T,
                             membership.rows =parcel.list$sub02$vox.des$Comm.rcd,
                             membership.cols =parcel.list$sub02$vox.des$Comm.rcd,
                             left.label.col = labelcol$sub02,
                             bottom.label.col = labelcol$sub02,
                             left.label.size = 0.08,
                             bottom.label.size = 0.05,
                             extreme.values.na = FALSE,
                             heat.lim = c(-.005, .005),
                             heat.pal = kovesi.diverging_bwr_40_95_c42(200),
                             heat.pal.values = c(0,0.35,0.5,0.65,1),
                             left.label.text.size = 3,
                             bottom.label.text.size = 2,
                             left.label.text.col = textcol$sub02,
                             bottom.label.text.col = textcol$sub02,
                             title="sub2: significant contribution")

```

```{r, grid_heat_sigfj1, echo=F, fig.height=8, fig.width=14}
gridExtra::grid.arrange(as.grob(heat_sigfj1_sub1$plot), as.grob(heat_sigfj1_sub2$plot), 
                        ncol=2,
                        top = textGrob("Node x Node Matrix of Factor Score w/ Sig Contribution: Dim 1",gp=gpar(fontsize=16,font=3)))
```

Smoothed Sig Factor Score (Dim 1)
```{r, sm_squaremat_sigfj1, echo=F, fig.show = 'hide'}
#--- the important variables are the ones that contribute more than or equal to the average
sm_heat_sigfj1_sub1 <- superheat(fj1_sub1_sig_sqmat, y.axis.reverse = T, 
                                 smooth.heat = T, smooth.heat.type = "mean",
                                 membership.rows =parcel.list$sub01$vox.des$Comm.rcd,
                                 membership.cols =parcel.list$sub01$vox.des$Comm.rcd,                    
                                 left.label.col = labelcol$sub01,
                                 bottom.label.col = labelcol$sub01,
                                 left.label.size = 0.08,
                                 bottom.label.size = 0.05,
                                 extreme.values.na = FALSE,
                                 heat.lim = c(-.005, .005),
                                 heat.pal = kovesi.diverging_bwr_40_95_c42(200),
                                 heat.pal.values = c(0,0.35,0.5,0.65,1),
                                 left.label.text.size = 3,
                                 bottom.label.text.size = 2,
                                 left.label.text.col = textcol$sub01,
                                 bottom.label.text.col = textcol$sub01, 
                                 title="Node x Node Matrix of factor scores - sub1")

sm_heat_sigfj1_sub2 <- superheat(fj1_sub2_sig_sqmat, y.axis.reverse = T,
                                 smooth.heat = T, smooth.heat.type = "mean",
                                 membership.rows =parcel.list$sub02$vox.des$Comm.rcd,
                                 membership.cols =parcel.list$sub02$vox.des$Comm.rcd,
                                 left.label.col = labelcol$sub02,
                                 bottom.label.col = labelcol$sub02,
                                 left.label.size = 0.08,
                                 bottom.label.size = 0.05,
                                 extreme.values.na = FALSE,
                                 heat.lim = c(-.005, .005),
                                 heat.pal = kovesi.diverging_bwr_40_95_c42(200),
                                 heat.pal.values = c(0,0.35,0.5,0.65,1),
                                 left.label.text.size = 3,
                                 bottom.label.text.size = 2,
                                 left.label.text.col = textcol$sub02,
                                 bottom.label.text.col = textcol$sub02,
                                 title="Node x Node Matrix of factor scores - sub2")

```

```{r, grid_smheat_sigfj1, echo=F, fig.height=8, fig.width=14}
gridExtra::grid.arrange(as.grob(sm_heat_sigfj1_sub1$plot), as.grob(sm_heat_sigfj1_sub2$plot), 
                        ncol=2,
                        top = textGrob("Smoothed Node x Node Matrix of Factor Score w/ Sig Contribution: Dim 1",gp=gpar(fontsize=16,font=3)))
```

Factor score (Dim 2) in square matrix that have significant contribution only

```{r, squaremat_sigfj2, echo=F, fig.show = 'hide'}
fj2_sub1_sig_sqmat <- vec2sqmat(fj_sig[gtlabel$subjects_label=="sub01",2])
fj2_sub2_sig_sqmat <- vec2sqmat(fj_sig[gtlabel$subjects_label=="sub02",2])

heat_sigfj2_sub1 <- superheat(fj2_sub1_sig_sqmat, y.axis.reverse = T,
                              membership.rows =parcel.list$sub01$vox.des$Comm.rcd,
                              membership.cols =parcel.list$sub01$vox.des$Comm.rcd,                    
                              left.label.col = labelcol$sub01,
                              bottom.label.col = labelcol$sub01,
                              left.label.size = 0.08,
                              bottom.label.size = 0.05,
                              extreme.values.na = FALSE,
                              heat.lim = c(-.005, .005),
                              heat.pal = kovesi.diverging_bwr_40_95_c42(200),
                              heat.pal.values = c(0,0.35,0.5,0.65,1),
                              left.label.text.size = 3,
                              bottom.label.text.size = 2,
                              left.label.text.col = textcol$sub01, 
                              bottom.label.text.col = textcol$sub01, 
                              title="sub1: significant contribution")

heat_sigfj2_sub2 <- superheat(fj2_sub2_sig_sqmat, y.axis.reverse = T,
                              membership.rows =parcel.list$sub02$vox.des$Comm.rcd,
                              membership.cols =parcel.list$sub02$vox.des$Comm.rcd,
                              left.label.col = labelcol$sub02,
                              bottom.label.col = labelcol$sub02,
                              left.label.size = 0.08,
                              bottom.label.size = 0.05,
                              extreme.values.na = FALSE,
                              heat.lim = c(-.005, .005),
                              heat.pal = kovesi.diverging_bwr_40_95_c42(200),
                              heat.pal.values = c(0,0.35,0.5,0.65,1),
                              left.label.text.size = 3,
                              bottom.label.text.size = 2,
                              left.label.text.col = textcol$sub02,
                              bottom.label.text.col = textcol$sub02,
                              title="sub2: significant contribution")
```

```{r, grid_heat_sigfj2, echo=F, fig.height=8, fig.width=14}
gridExtra::grid.arrange(as.grob(heat_sigfj2_sub1$plot), as.grob(heat_sigfj2_sub2$plot), 
                        ncol=2,
                        top = textGrob("Node x Node Matrix of Factor Score w/ Sig Contribution: Dim 2",gp=gpar(fontsize=16,font=3)))
```

Smoothed Sig Factor Score (Dim 2)
```{r, sm_squaremat_sigfj2, echo=F, fig.show = 'hide'}
#--- the important variables are the ones that contribute more than or equal to the average
sm_heat_sigfj2_sub1 <- superheat(fj2_sub1_sig_sqmat, y.axis.reverse = T, 
                                 smooth.heat = T, smooth.heat.type = "mean",
                                 membership.rows =parcel.list$sub01$vox.des$Comm.rcd,
                                 membership.cols =parcel.list$sub01$vox.des$Comm.rcd,                    
                                 left.label.col = labelcol$sub01,
                                 bottom.label.col = labelcol$sub01,
                                 left.label.size = 0.08,
                                 bottom.label.size = 0.05,
                                 extreme.values.na = FALSE,
                                 heat.lim = c(-.005, .005),
                                 heat.pal = kovesi.diverging_bwr_40_95_c42(200),
                                 heat.pal.values = c(0,0.35,0.5,0.65,1),
                                 left.label.text.size = 3,
                                 bottom.label.text.size = 2,
                                 left.label.text.col = textcol$sub01,
                                 bottom.label.text.col = textcol$sub01, 
                                 title="Node x Node Matrix of 2nd component factor scores - sub1")

sm_heat_sigfj2_sub2 <- superheat(fj2_sub2_sig_sqmat, y.axis.reverse = T,
                                 smooth.heat = T, smooth.heat.type = "mean",
                                 membership.rows =parcel.list$sub02$vox.des$Comm.rcd,
                                 membership.cols =parcel.list$sub02$vox.des$Comm.rcd,
                                 left.label.col = labelcol$sub02,
                                 bottom.label.col = labelcol$sub02,
                                 left.label.size = 0.08,
                                 bottom.label.size = 0.05,
                                 extreme.values.na = FALSE,
                                 heat.lim = c(-.005, .005),
                                 heat.pal = kovesi.diverging_bwr_40_95_c42(200),
                                 heat.pal.values = c(0,0.35,0.5,0.65,1),
                                 left.label.text.size = 3,
                                 bottom.label.text.size = 2,
                                 left.label.text.col = textcol$sub02,
                                 bottom.label.text.col = textcol$sub02,
                                 title="Node x Node Matrix of 2nd component factor scores - sub2")

```

```{r, grid_smheat_sigfj2, echo=F, fig.height=8, fig.width=14}
gridExtra::grid.arrange(as.grob(sm_heat_sigfj2_sub1$plot), as.grob(sm_heat_sigfj2_sub2$plot), 
                        ncol=2,
                        top = textGrob("Smoothed Node x Node Matrix of Factor Score w/ Sig Contribution: Dim 2",gp=gpar(fontsize=16,font=3)))
```